name: app_doc_1
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # google_font
  google_fonts: ^4.0.3
  flutter_native_splash: ^2.2.19
  get: ^4.6.5
  smooth_page_indicator: ^1.0.1
  liquid_swipe: ^3.0.0
  flutter_otp_text_field: ^1.1.1
  # firebase
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.1.1
  image_picker: ^0.8.7+2
  google_sign_in: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/komp_logo2.png
  image_dark: assets/images/komp_logo2.png

  android_12:
    image: assets/images/komp_logo2.png
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/komp_logo2.png
    icon_background_color_dark: "#272727"


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/forget_password/
    - assets/images/dashboard/
    - assets/images/komp_logo2.png
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  
  
